from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserRegistrationView,
    UserProfileView,
    change_password,
    CreditTransactionViewSet,
    SubscriptionPlanViewSet,
    UserDashboardView,
    dashboard_stats,
    dashboard_usage,
    recent_transactions,
    admin_stats,
    admin_users,
    admin_payments,
    admin_voices,
    admin_activity,
    admin_revenue_chart,
    admin_create_user,
    admin_update_user,
    admin_delete_user,
    admin_add_credits,
    admin_activity_logs,
    admin_toggle_user_status,
    admin_login_as_user,
    platform_settings_public,
    admin_get_platform_settings,
    admin_update_platform_settings,
    admin_test_payment_gateway,
    admin_test_smtp,
    get_notifications,
    get_unread_count,
    mark_notification_read,
    mark_all_notifications_read,
    delete_notification,
    delete_all_notifications,
    create_announcement,
    get_active_announcements,
    get_all_announcements,
    delete_announcement,
    send_marketing_email,
    get_email_campaigns,
    delete_email_campaign,
    get_campaign_details,
    upload_email_list,
    get_email_lists,
    delete_email_list,
    track_click,
    get_click_analytics,
    database_settings_view,
    test_database_connection,
    get_database_tables,
    get_table_data,
    execute_sql_query,
    update_table_record,
    delete_table_record,
    get_supported_languages,
    admin_get_all_languages,
    admin_toggle_language,
    start_model_training,
    get_training_status,
    admin_voice_cloning_status,
    admin_delete_voice_cloning,
    admin_voice_clone_details,
    admin_voice_clone_download
)

router = DefaultRouter()
router.register(r'credit-transactions', CreditTransactionViewSet, basename='credit-transaction')
router.register(r'subscription-plans', SubscriptionPlanViewSet, basename='subscription-plan')

app_name = 'accounts'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('change-password/', change_password, name='change-password'),
    path('dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('dashboard/stats/', dashboard_stats, name='dashboard-stats'),
    path('dashboard/usage/', dashboard_usage, name='dashboard-usage'),
    path('transactions/recent/', recent_transactions, name='recent-transactions'),
    # Admin dashboard endpoints
    path('admin/stats/', admin_stats, name='admin-stats'),
    path('admin/users/', admin_users, name='admin-users'),
    path('admin/payments/', admin_payments, name='admin-payments'),
    path('admin/voices/', admin_voices, name='admin-voices'),
    path('admin/activity/', admin_activity, name='admin-activity'),
    path('admin/revenue-chart/', admin_revenue_chart, name='admin-revenue-chart'),
    # Admin user management endpoints
    path('admin/users/create/', admin_create_user, name='admin-create-user'),
    path('admin/users/<int:user_id>/update/', admin_update_user, name='admin-update-user'),
    path('admin/users/<int:user_id>/delete/', admin_delete_user, name='admin-delete-user'),
    path('admin/users/<int:user_id>/toggle-status/', admin_toggle_user_status, name='admin-toggle-user-status'),
    path('admin/users/<int:user_id>/add-credits/', admin_add_credits, name='admin-add-credits'),
    path('admin/users/login-as/', admin_login_as_user, name='admin-login-as-user'),
    # Admin activity logs
    path('admin/activity-logs/', admin_activity_logs, name='admin-activity-logs'),
    # Voice Cloning Status Tracking
    path('admin/voice-cloning-status/', admin_voice_cloning_status, name='admin-voice-cloning-status'),
    path('admin/voice-cloning/delete/', admin_delete_voice_cloning, name='admin-delete-voice-cloning'),
    path('admin/voice-clones/<str:audio_id>/', admin_voice_clone_details, name='admin-voice-clone-details'),
    path('admin/voice-clones/<str:audio_id>/download/', admin_voice_clone_download, name='admin-voice-clone-download'),
    # Platform settings
    path('platform-settings/', platform_settings_public, name='platform-settings-public'),
    path('admin/platform-settings/', admin_get_platform_settings, name='admin-get-platform-settings'),
    path('admin/platform-settings/update/', admin_update_platform_settings, name='admin-update-platform-settings'),
    path('admin/platform-settings/test-gateway/', admin_test_payment_gateway, name='admin-test-payment-gateway'),
    path('admin/test-smtp/', admin_test_smtp, name='admin-test-smtp'),
    # Notifications
    path('notifications/', get_notifications, name='get-notifications'),
    path('notifications/unread-count/', get_unread_count, name='get-unread-count'),
    path('notifications/<int:notification_id>/read/', mark_notification_read, name='mark-notification-read'),
    path('notifications/mark-all-read/', mark_all_notifications_read, name='mark-all-read'),
    path('notifications/<int:notification_id>/delete/', delete_notification, name='delete-notification'),
    path('notifications/delete-all/', delete_all_notifications, name='delete-all-notifications'),
    # Announcements
    path('announcements/create/', create_announcement, name='create-announcement'),
    path('announcements/active/', get_active_announcements, name='active-announcements'),
    path('announcements/all/', get_all_announcements, name='all-announcements'),
    path('announcements/<int:announcement_id>/delete/', delete_announcement, name='delete-announcement'),
    # Email Marketing
    path('admin/send-marketing-email/', send_marketing_email, name='send-marketing-email'),
    path('admin/email-campaigns/', get_email_campaigns, name='get-email-campaigns'),
    path('admin/email-campaigns/<int:campaign_id>/', get_campaign_details, name='get-campaign-details'),
    path('admin/email-campaigns/<int:campaign_id>/delete/', delete_email_campaign, name='delete-email-campaign'),
    # CSV Email Lists
    path('admin/email-lists/upload/', upload_email_list, name='upload-email-list'),
    path('admin/email-lists/', get_email_lists, name='get-email-lists'),
    path('admin/email-lists/<int:list_id>/delete/', delete_email_list, name='delete-email-list'),
    # Click Tracking
    path('track-click/<str:token>/', track_click, name='track-click'),
    path('admin/email-campaigns/<int:campaign_id>/analytics/', get_click_analytics, name='click-analytics'),
    # Database Management
    path('admin/database/settings/', database_settings_view, name='database-settings'),
    path('admin/database/test-connection/', test_database_connection, name='test-database-connection'),
    path('admin/database/tables/', get_database_tables, name='get-database-tables'),
    path('admin/database/tables/<str:table_name>/', get_table_data, name='get-table-data'),
    path('admin/database/execute-query/', execute_sql_query, name='execute-sql-query'),
    path('admin/database/tables/<str:table_name>/update/', update_table_record, name='update-table-record'),
    path('admin/database/tables/<str:table_name>/<int:record_id>/delete/', delete_table_record, name='delete-table-record'),
    # Language Management
    path('languages/', get_supported_languages, name='get-supported-languages'),
    path('admin/languages/', admin_get_all_languages, name='admin-get-all-languages'),
    path('admin/languages/<int:language_id>/toggle/', admin_toggle_language, name='admin-toggle-language'),
    # Model Training
    path('admin/start-training/', start_model_training, name='start-model-training'),
    path('admin/training-status/<str:training_id>/', get_training_status, name='get-training-status'),
    path('', include(router.urls)),
]
