# Generated by Django 5.2.7 on 2025-11-18 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_apikey'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=20)),
                ('payment_type', models.CharField(choices=[('credit', 'Credit Purchase'), ('subscription', 'Subscription')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('transaction_id', models.CharField(help_text='User provided transaction ID', max_length=255)),
                ('account_number', models.CharField(help_text="User's JazzCash/Easypaisa account number", max_length=20)),
                ('payment_screenshot', models.ImageField(help_text='Screenshot of payment confirmation', upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/reason for rejection')),
                ('credits_to_award', models.IntegerField(default=0)),
                ('credits_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment_requests', to='payments.creditpackage')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment_requests', to='accounts.subscriptionplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Payment Request',
                'verbose_name_plural': 'Manual Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
