# Generated by Django 5.2.7 on 2025-11-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_platformsettings_usd_to_pkr_rate'),
        ('payments', '0002_manualpaymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.creditpackage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.subscriptionplan'),
        ),
    ]
