# Generated by Django 5.2.7 on 2025-12-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_package_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_code',
            field=models.CharField(blank=True, help_text='Stripe/PayPal error code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Reason for payment failure', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
