# Generated by Django 5.2.7 on 2025-10-13 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], max_length=10)),
                ('accent', models.CharField(max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('voice_file', models.FileField(upload_to='library_voices/')),
                ('embedding_file', models.FileField(blank=True, null=True, upload_to='library_embeddings/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preview_audio', models.FileField(blank=True, null=True, upload_to='library_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Voice Libraries',
            },
        ),
        migrations.CreateModel(
            name='ClonedVoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='cloned_voices/')),
                ('embedding_file', models.FileField(blank=True, null=True, upload_to='voice_embeddings/')),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('voice_source', models.CharField(choices=[('library', 'Library Voice'), ('cloned', 'Cloned Voice')], max_length=20)),
                ('audio_file', models.FileField(upload_to='generated_audio/')),
                ('speed', models.FloatField(default=1.0)),
                ('pitch', models.FloatField(default=1.0)),
                ('tone', models.FloatField(default=1.0)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('characters_used', models.IntegerField()),
                ('credits_used', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voices.clonedvoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_audios', to=settings.AUTH_USER_MODEL)),
                ('library_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voices.voicelibrary')),
            ],
            options={
                'verbose_name_plural': 'Generated Audios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voices.generatedaudio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voice Generation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
