# Generated by Django 5.2.7 on 2025-10-16 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedaudio',
            name='generation_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters used for audio generation (temperature, top_p, etc.)'),
        ),
        migrations.AlterField(
            model_name='generatedaudio',
            name='audio_file',
            field=models.FileField(upload_to='generated_audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='generatedaudio',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='generatedaudio',
            name='voice_source',
            field=models.CharField(choices=[('library', 'Library Voice'), ('cloned', 'Cloned Voice'), ('custom', 'Custom Voice Reference')], default='custom', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generatedaudio',
            index=models.Index(fields=['user', '-created_at'], name='voices_gene_user_id_37e598_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedaudio',
            index=models.Index(fields=['-created_at'], name='voices_gene_created_f49e00_idx'),
        ),
    ]
