# Generated by Django 5.2.7 on 2025-10-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_generatedaudio_generation_params_and_more'),
    ]

    operations = [
    ]
