# Generated by Django 5.2.7 on 2025-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0003_auto_20251017_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedaudio',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='estimated_time',
            field=models.IntegerField(blank=True, help_text='Estimated time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage 0-100'),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedaudio',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
