# Generated by Django 4.2.16 on 2025-11-09 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voices', '0004_generatedaudio_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedaudio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_audios', to=settings.AUTH_USER_MODEL),
        ),
    ]
