# Generated by Django 4.2.16 on 2025-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0005_alter_generatedaudio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_audio/%Y/%m/%d/'),
        ),
    ]
