# Generated by Django 5.2.7 on 2025-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0006_alter_generatedaudio_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clonedvoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voice_images/'),
        ),
    ]
