# Generated by Django 5.2.7 on 2025-11-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0007_clonedvoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicelibrary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='library_images/'),
        ),
    ]
