# Generated by Django 5.2.7 on 2025-10-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this user from public listings'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.subscriptionplan'),
        ),
    ]
