# Generated by Django 5.2.7 on 2025-10-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_hidden_user_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('credits_added', 'Credits Added'), ('credits_deducted', 'Credits Deducted'), ('subscription_changed', 'Subscription Changed'), ('subscription_cancelled', 'Subscription Cancelled'), ('voice_deleted', 'Voice Deleted'), ('payment_refunded', 'Payment Refunded'), ('admin_login', 'Admin Login'), ('settings_updated', 'Settings Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('voice_cloned', 'Voice Cloned'), ('audio_generated', 'Audio Generated'), ('payment_completed', 'Payment Completed')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_ac_created_91b66e_idx'), models.Index(fields=['admin_user', '-created_at'], name='accounts_ac_admin_u_9a725b_idx'), models.Index(fields=['target_user', '-created_at'], name='accounts_ac_target__c89eab_idx'), models.Index(fields=['action'], name='accounts_ac_action_fde492_idx')],
            },
        ),
    ]
