# Generated by Django 5.2.7 on 2025-10-16 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_calculation_type', models.CharField(choices=[('per_character', 'Per Character'), ('per_word', 'Per Word'), ('per_letter', 'Per Letter')], default='per_character', help_text='How to calculate credits for text-to-speech', max_length=20)),
                ('credits_per_unit', models.IntegerField(default=1, help_text='Number of credits per character/word/letter')),
                ('free_trial_credits', models.IntegerField(default=1000, help_text='Free credits given to new users')),
                ('free_trial_voice_clones', models.IntegerField(default=1, help_text='Free voice clones allowed for new users')),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=255)),
                ('paypal_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('jazzcash_enabled', models.BooleanField(default=False)),
                ('jazzcash_merchant_id', models.CharField(blank=True, max_length=255)),
                ('jazzcash_password', models.CharField(blank=True, max_length=255)),
                ('jazzcash_integrity_salt', models.CharField(blank=True, max_length=255)),
                ('easypaisa_enabled', models.BooleanField(default=False)),
                ('easypaisa_store_id', models.CharField(blank=True, max_length=255)),
                ('easypaisa_password', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
