# Generated by Django 5.2.7 on 2025-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='diffusion_steps',
            field=models.IntegerField(default=25, help_text='Number of diffusion steps for quality (5-50)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='do_sample',
            field=models.BooleanField(default=True, help_text='Enable sampling during generation'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='inference_cfg_rate',
            field=models.FloatField(default=0.7, help_text='Inference CFG rate for classifier-free guidance (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='interval_silence',
            field=models.IntegerField(default=200, help_text='Silence interval between segments in milliseconds (0-1000)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='length_penalty',
            field=models.FloatField(default=0.0, help_text='Length penalty (-2.0 to 2.0)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_mel_tokens',
            field=models.IntegerField(default=1500, help_text='Maximum mel tokens for audio generation (500-5000)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_text_tokens_per_segment',
            field=models.IntegerField(default=120, help_text='Maximum text tokens per segment (50-300)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='num_beams',
            field=models.IntegerField(default=3, help_text='Number of beams for beam search (1-10)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='repetition_penalty',
            field=models.FloatField(default=10.0, help_text='Repetition penalty (1.0-20.0)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='temperature',
            field=models.FloatField(default=0.8, help_text='Temperature for sampling (0.1-2.0)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='top_k',
            field=models.IntegerField(default=30, help_text='Top-k sampling value (1-100)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='top_p',
            field=models.FloatField(default=0.8, help_text='Top-p (nucleus sampling) value (0.0-1.0)'),
        ),
    ]
