# Generated by Django 5.2.7 on 2025-10-22 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Email body (supports HTML)')),
                ('recipients_type', models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users'), ('inactive', 'Inactive Users'), ('free', 'Free Plan Users'), ('basic', 'Basic Plan Users'), ('pro', 'Pro Plan Users')], default='all', max_length=20)),
                ('sent_count', models.IntegerField(default=0, help_text='Number of emails successfully sent')),
                ('failed_count', models.IntegerField(default=0, help_text='Number of emails that failed to send')),
                ('is_test', models.BooleanField(default=False, help_text='Whether this was a test email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_snapshot', models.JSONField(blank=True, default=list, help_text='List of user emails who received this campaign')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
