# Generated by Django 5.2.7 on 2025-10-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_google_oauth_and_smtp_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='pending_count',
            field=models.IntegerField(default=0, help_text='Number of emails pending to send'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the campaign was sent', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='body',
            field=models.TextField(help_text='Email body (supports HTML and template variables like {{username}}, {{credits}}, {{deal_amount}})'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipients_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='List of recipients with their data: [{email, username, credits, status}]'),
        ),
    ]
