# Generated by Django 5.2.7 on 2025-10-25 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_email_campaign_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='click_count',
            field=models.IntegerField(default=0, help_text='Number of link clicks tracked'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='recipient_source',
            field=models.CharField(choices=[('website', 'Website Users Only'), ('csv', 'CSV List Only'), ('both', 'Both Website & CSV')], default='website', help_text='Send to website users, CSV list, or both', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='unique_clicks',
            field=models.IntegerField(default=0, help_text='Unique users who clicked'),
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this email list', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this list')),
                ('csv_file', models.FileField(help_text='CSV file with email,username columns', upload_to='email_lists/')),
                ('total_emails', models.IntegerField(default=0, help_text='Total emails in this list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emails_data', models.JSONField(default=list, help_text='List of {email, username} from CSV')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_email_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='csv_list',
            field=models.ForeignKey(blank=True, help_text='CSV email list to use', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.emaillist'),
        ),
        migrations.CreateModel(
            name='EmailClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the person who clicked', max_length=254)),
                ('clicked_url', models.URLField(help_text='URL that was clicked')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('tracking_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='accounts.emailcampaign')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['campaign', 'email'], name='accounts_em_campaig_07ad94_idx'), models.Index(fields=['tracking_token'], name='accounts_em_trackin_1bb661_idx')],
            },
        ),
    ]
