# Generated by Django 5.2.7 on 2025-10-25 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_csv_email_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.CharField(choices=[('sqlite', 'SQLite (Default)'), ('mysql', 'MySQL')], default='sqlite', help_text='Select which database to use', max_length=20)),
                ('mysql_enabled', models.BooleanField(default=False, help_text='Enable MySQL database')),
                ('mysql_host', models.CharField(default='localhost', help_text='MySQL host address', max_length=255)),
                ('mysql_port', models.IntegerField(default=3306, help_text='MySQL port')),
                ('mysql_database', models.CharField(blank=True, help_text='MySQL database name', max_length=255)),
                ('mysql_user', models.CharField(blank=True, help_text='MySQL username', max_length=255)),
                ('mysql_password', models.CharField(blank=True, help_text='MySQL password', max_length=255)),
                ('last_connection_test', models.DateTimeField(blank=True, help_text='Last successful connection test', null=True)),
                ('connection_status', models.CharField(default='untested', help_text='Connection status', max_length=20)),
                ('connection_message', models.TextField(blank=True, help_text='Connection status message')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Settings',
                'verbose_name_plural': 'Database Settings',
            },
        ),
    ]
