# Generated by Django 5.2.7 on 2025-11-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_is_verified_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text="ISO language code (e.g., 'en', 'zh', 'es')", max_length=10, unique=True, verbose_name='Language Code')),
                ('language_name', models.CharField(help_text="Full language name (e.g., 'English', 'Chinese')", max_length=100, verbose_name='Language Name')),
                ('native_name', models.CharField(help_text="Language name in native script (e.g., '中文', 'Español')", max_length=100, verbose_name='Native Name')),
                ('flag_emoji', models.CharField(default='🌐', help_text='Flag emoji for the language', max_length=10, verbose_name='Flag Emoji')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this language is available for users', verbose_name='Enabled')),
                ('is_trained', models.BooleanField(default=False, help_text='Whether a model is trained for this language', verbose_name='Model Trained')),
                ('model_path', models.CharField(blank=True, help_text='Path to the trained model file', max_length=500, null=True, verbose_name='Model Path')),
                ('training_status', models.CharField(choices=[('not_started', 'Not Started'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20, verbose_name='Training Status')),
                ('quality_score', models.FloatField(default=0.0, help_text='Model quality score (0-100)', verbose_name='Quality Score')),
                ('description', models.TextField(blank=True, help_text='Additional information about this language model', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supported Language',
                'verbose_name_plural': 'Supported Languages',
                'ordering': ['language_name'],
            },
        ),
    ]
