# Generated by Django 5.2.7 on 2025-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_supportedlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('basic', 'Basic'), ('pro', 'Pro'), ('yearly', 'Yearly')], max_length=20, unique=True),
        ),
    ]
