# Generated by Django 5.2.7 on 2025-11-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='easypaisa_account_number',
            field=models.CharField(blank=True, help_text='Easypaisa account number for manual payments', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='easypaisa_account_title',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='jazzcash_account_number',
            field=models.CharField(blank=True, help_text='JazzCash account number for manual payments', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='jazzcash_account_title',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=255),
        ),
    ]
