# Generated by Django 5.2.7 on 2025-11-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_platformsettings_easypaisa_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='usd_to_pkr_rate',
            field=models.DecimalField(decimal_places=2, default=278.0, help_text='USD to PKR exchange rate for manual payments', max_digits=10),
        ),
    ]
