# Generated by Django 5.2.7 on 2025-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_platformsettings_usd_to_pkr_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('basic', 'Basic'), ('pro', 'Pro'), ('yearly', 'Yearly')], default='free', max_length=20),
        ),
    ]
