# Generated by Django 5.2.7 on 2025-10-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Font Awesome Icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'API Feature',
                'verbose_name_plural': 'API Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='APISection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Powerful API for Developers', max_length=300, verbose_name='Title')),
                ('subtitle', models.TextField(default='Integrate voice generation into your applications with our simple REST API', verbose_name='Subtitle')),
                ('code_example', models.TextField(help_text='Python or other code example', verbose_name='Code Example')),
                ('code_language', models.CharField(default='Python', max_length=50, verbose_name='Code Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'API Section',
                'verbose_name_plural': 'API Sections',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Get Started?', max_length=300, verbose_name='Title')),
                ('subtitle', models.TextField(default='Sign up now and get 1,000 free credits plus 1 free voice clone!', verbose_name='Subtitle')),
                ('subtitle_extra', models.CharField(blank=True, default='No credit card required.', max_length=200, verbose_name='Extra Subtitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='DemoVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sarah - Female (American)', max_length=200, verbose_name='Voice Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='demo_voices/', verbose_name='Audio File')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Demo Voice',
                'verbose_name_plural': 'Demo Voices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='e.g., fa-magic, fa-clone', max_length=50, verbose_name='Font Awesome Icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='AI-Powered Voice Technology', max_length=200, verbose_name='Badge Text')),
                ('title', models.CharField(default='Transform Text into Natural, Human-Like Speech', max_length=300, verbose_name='Title')),
                ('subtitle', models.TextField(default='Clone any voice and generate professional-quality speech with our advanced AI technology. Perfect for content creators, businesses, and developers.', verbose_name='Subtitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Step Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_emoji', models.CharField(help_text='e.g., 🇺🇸', max_length=10, verbose_name='Flag Emoji')),
                ('language_name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Language Support',
                'verbose_name_plural': 'Language Supports',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LiveStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Font Awesome Icon')),
                ('value', models.IntegerField(help_text='The number to count up to', verbose_name='Value')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('trend_percentage', models.IntegerField(default=0, verbose_name='Trend Percentage')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Live Statistic',
                'verbose_name_plural': 'Live Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('price', models.CharField(help_text='e.g., $0, $29', max_length=50, verbose_name='Price')),
                ('period', models.CharField(default='per month', max_length=50, verbose_name='Period')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Plan')),
                ('badge_text', models.CharField(blank=True, help_text='e.g., Most Popular', max_length=50, verbose_name='Badge Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QualityComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_type', models.CharField(choices=[('bad', 'Traditional TTS (Bad)'), ('good', 'Index-TTS2 AI (Good)')], max_length=10, verbose_name='Comparison Type')),
                ('text', models.CharField(max_length=300, verbose_name='Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Quality Comparison Point',
                'verbose_name_plural': 'Quality Comparison Points',
                'ordering': ['comparison_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g., 10M+, 50K+, 99.9%', max_length=50, verbose_name='Number')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('author_name', models.CharField(max_length=200, verbose_name='Author Name')),
                ('author_title', models.CharField(max_length=200, verbose_name='Author Title')),
                ('author_initials', models.CharField(help_text='e.g., JD', max_length=3, verbose_name='Author Initials')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Font Awesome Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Trust Badge',
                'verbose_name_plural': 'Trust Badges',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Font Awesome Icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('slide_number', models.IntegerField(default=1, help_text='Which carousel slide (1 or 2)', verbose_name='Slide Number')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
                'ordering': ['slide_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='See It In Action', max_length=300, verbose_name='Title')),
                ('subtitle', models.TextField(default='Watch how easy it is to clone a voice and generate professional audio in minutes', verbose_name='Subtitle')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video File')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Video Thumbnail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Video Section',
                'verbose_name_plural': 'Video Sections',
            },
        ),
        migrations.CreateModel(
            name='CTAFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Font Awesome Icon')),
                ('text', models.CharField(max_length=300, verbose_name='Feature Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('cta_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homepage.ctasection')),
            ],
            options={
                'verbose_name': 'CTA Feature',
                'verbose_name_plural': 'CTA Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Feature Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homepage.herosection')),
            ],
            options={
                'verbose_name': 'Hero Feature',
                'verbose_name_plural': 'Hero Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Feature Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homepage.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Feature Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('video_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homepage.videosection')),
            ],
            options={
                'verbose_name': 'Video Feature',
                'verbose_name_plural': 'Video Features',
                'ordering': ['order'],
            },
        ),
    ]
