# Generated by Django 5.2.7 on 2025-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order', '-is_active', '-updated_at'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(blank=True, default='Get Started', max_length=100, verbose_name='Primary Button Text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_button_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Primary Button URL'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Secondary Button Text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Secondary Button URL'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='icon',
            field=models.CharField(default='fa-upload', help_text='e.g., fa-upload, fa-magic, fa-download', max_length=50, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='icon',
            field=models.CharField(default='fa-users', help_text='e.g., fa-users, fa-microphone', max_length=50, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='step_number',
            field=models.IntegerField(default=1, verbose_name='Step Number'),
        ),
    ]
