# Generated by Django 5.2.7 on 2025-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_herosection_options_herosection_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosection',
            options={'ordering': ['order'], 'verbose_name': 'Video Section', 'verbose_name_plural': 'Video Sections'},
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text',
            field=models.CharField(default='Get Started', max_length=100, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_url',
            field=models.CharField(default='#', max_length=200, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular/Recommended'),
        ),
        migrations.AddField(
            model_name='videosection',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
