# Generated by Django 5.2.7 on 2025-10-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_videosection_options_pricingplan_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('subtitle', models.TextField(verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('button_text', models.CharField(default='Get Started', max_length=100, verbose_name='Button Text')),
                ('button_url', models.CharField(default='#', max_length=200, verbose_name='Button URL')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name='Background Image')),
                ('background_color', models.CharField(default='#000000', help_text='Hex color code', max_length=50, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=50, verbose_name='Text Color')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order'],
            },
        ),
    ]
