"""
Django settings for voice_cloning project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ga_4=l8e6jv+@px-$a6d7em0w#7fn_fn9%n0_3=!9r@^6gvs@%'

# SECURITY WARNING: don't run with debug turned on in production!
# Allow DEBUG to be set via environment variable for production
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '195.139.22.91',
    'talkstudio.ai',
    'www.talkstudio.ai',
    '.talkstudio.ai',  # Allow all subdomains
]

# Ensure ALLOWED_HOSTS is never empty
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Local apps
    'accounts',
    'voices',
    'tts_engine',
    'payments',
    'support',
    'homepage',
]

SITE_ID = 1  # Use default site (will be talkstudio.ai on production)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'accounts.middleware.UserActivityMiddleware',  # Track user online/offline status
]

ROOT_URLCONF = 'voice_cloning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.platform_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'voice_cloning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'العربية'),  # Arabic
    ('bn', 'বাংলা'),  # Bengali
    ('es', 'Español'),  # Spanish
    ('fr', 'Français'),  # French
    ('hi', 'हिन्दी'),  # Hindi
    ('ur', 'اردو'),  # Urdu
    ('zh-hans', '简体中文'),  # Simplified Chinese
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Language cookie settings
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None  # Session cookie
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = 'Lax'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Session Settings - Prevent Auto Logout
SESSION_COOKIE_AGE = 86400 * 7  # 7 days (in seconds)
SESSION_SAVE_EVERY_REQUEST = True  # Keep session alive on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Don't expire when browser closes
SESSION_COOKIE_HTTPONLY = True  # Security: JavaScript can't access session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Django Allauth Settings (Updated to new format)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # No email verification - users can signup and login immediately
LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip email verification for social logins

# Email settings (Dynamically loads from database via custom backend)
EMAIL_BACKEND = 'voice_cloning.email_backend.ConsoleOrSMTPBackend'
DEFAULT_FROM_EMAIL = 'Talk Studio Platform <noreply@voicecloning.com>'
EMAIL_TIMEOUT = 10  # 10 seconds timeout for email sending

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "https://talkstudio.ai",
    "https://www.talkstudio.ai",
    "http://195.139.22.91"
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://195.139.22.91",
    "https://talkstudio.ai",
    "https://www.talkstudio.ai",
]
# settings.py
CELERY_TASK_ROUTES = {
    'voices.tasks.tts_generation_task': {'queue': 'gpu0'},   # ← yeh line add karo
    # agar 2 GPU hain toh neeche wala bhi
    'voices.tasks.tts_generation_task': {'queue': 'gpu1'},
}
# HTTPS/SSL Settings for Production
# Tell Django to trust the X-Forwarded-Proto header from proxy (nginx/apache)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Force HTTPS redirects in production (only when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Celery Settings (for async tasks)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Base URL for payment callbacks
# Use environment variable if set, otherwise detect based on DEBUG mode
if os.getenv('BASE_URL'):
    BASE_URL = os.getenv('BASE_URL')
elif DEBUG:
    BASE_URL = 'http://localhost:8000'
else:
    BASE_URL = 'https://talkstudio.ai'

# Payment Gateway Settings
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')  # Alias for templates
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')  # 'sandbox' or 'live'

# JazzCash & Easypaisa (Pakistani payment gateways)
JAZZCASH_MERCHANT_ID = os.getenv('JAZZCASH_MERCHANT_ID', '')
JAZZCASH_PASSWORD = os.getenv('JAZZCASH_PASSWORD', '')
JAZZCASH_INTEGRITY_SALT = os.getenv('JAZZCASH_INTEGRITY_SALT', '')

EASYPAISA_STORE_ID = os.getenv('EASYPAISA_STORE_ID', '')
EASYPAISA_PASSWORD = os.getenv('EASYPAISA_PASSWORD', '')

# Google OAuth Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

# TTS Engine Settings
MAX_TEXT_LENGTH = 50000  # 50k characters
MAX_AUDIO_DURATION = 300  # 5 minutes for Talk Studio
MIN_AUDIO_DURATION = 3  # 3 seconds minimum

# Credit System
CREDITS_PER_CHARACTER = 1  # 1 character = 1 credit
FREE_TRIAL_CREDITS = 1000  # Free users get 1000 credits
FREE_TRIAL_VOICE_CLONES = 1  # Free users get 1 voice clone

# File Upload Settings
MAX_AUDIO_FILE_SIZE = 50 * 1024 * 1024  # 50 MB
ALLOWED_AUDIO_FORMATS = ['.wav', '.mp3', '.flac', '.ogg', '.m4a']

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'voice_cloning.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'tts_engine': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_USE_SESSIONS = False  # Store CSRF token in cookies, not sessions
CSRF_COOKIE_SAMESITE = 'Lax'  # Protect against CSRF attacks

# Security Settings (Enable in production)
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'

# TTS API Configuration (External API instead of local model)
# Set these environment variables or configure in admin panel
TTS_API_URL = os.environ.get('TTS_API_URL', '')  # External TTS API endpoint
TTS_API_KEY = os.environ.get('TTS_API_KEY', '')  # API authentication key
TTS_API_TIMEOUT = int(os.environ.get('TTS_API_TIMEOUT', '300'))  # Request timeout (seconds)

# File Upload Settings for Model Training
# Maximum file upload size: 2GB
DATA_UPLOAD_MAX_MEMORY_SIZE = 2147483648  # 2GB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 2147483648  # 2GB in bytes
